blank_issues_enabled: true
contact_links:
  - name: Questions and discussions
    url: https://github.com/javinnav/pi-profiles-manager/discussions
    about: Ask questions and discuss ideas with the community.
